---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: astro-web
spec:
  selector:
    matchLabels:
      run: astro-web
  replicas: 
  template:
    metadata:
      labels:
        run: astro-web
    spec:
      containers:
      - name: astro-web
        image: rtovey/astro-web:1.0
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 300m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: astro-api
spec:
  selector:
    matchLabels:
      run: astro-api
  template:
    metadata:
      labels:
        run: astro-api
    spec:
      containers:
      - name: astro-api
        image: rtovey/astro-api:1.0
        ports:
        - containerPort: 8090
        livenessProbe:
          httpGet:
            path: /api/moon/phase
            port: 8090
          initialDelaySeconds: 3
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 300m
---
