---
apiVersion: v1
kind: Service
metadata:
  name: astro-web
  labels:
    run: astro-web
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: astro-web
---
apiVersion: v1
kind: Service
metadata:
  name: astro-api
  labels:
    run: astro-api
spec:
  type: LoadBalancer
  ports:
  - port: 8090
    targetPort: 8090
    protocol: TCP
  selector:
    run: astro-api
---
